/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;
import Estructuras.*;
import Estructuras_Socket.Molde;
import estructuras_Socket.*;
import Estructuras_Tablero.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.net.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
/**
 *
 * @author kenne
 */
public class NewJFrame extends javax.swing.JFrame {
    private ArrayList<Point> lista1 = new ArrayList<Point>();
    private ArrayList<Integer> lista = new ArrayList<Integer>();
    private Puntos puntos=new Puntos();
private Molde mensaje;
private Socket socket;
private Conexion_Servidor conexion__servidor;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        
        initComponents();
        this.add(puntos);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 700));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1)))
                .addContainerGap(317, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mensaje= new Molde();
        socket= new Socket();
        conexion__servidor=new Conexion_Servidor(socket,mensaje);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
       // System.out.println(evt.getX());
        //System.out.println(evt.getY());
     
        int y=0;
	    int x=0;
        if (lista.size()<=4){for (int i =35; i<600; i+=100) {
	    	if (i-30 <evt.getX() & evt.getX()<i+30) {
	    		x=i+10;break;}}
	    for (int j=115;j<700;j+=100) {
	    	if (j-30 <evt.getY() & evt.getY()<j+30) {
	    		y=j+20;break;}}
	    lista.add(x);
            lista.add(y);
            //System.out.println(evt.getX());
        System.out.println("Hola3");
        //System.out.println(evt.getY());
        System.out.println("Hola4");
            if (lista.size()==4){
                System.out.println("NOSE");
            puntos.dibujar( lista);
             //System.out.println(evt.getX());
       // System.out.println(evt.getY());
        lista.clear();
        }}
        //verificar(x,y);}
        
    }//GEN-LAST:event_formMouseClicked
 /*public void verificar(int x,int y){
        Graphics g = this.getGraphics();
        //g.drawLine(200, 200,300,300);*/
	    //*************DIBUJAR LINEA********************//
	    //OBTENER PUNTOS
	    /*{mensaje.setNombre("Kenneth");
	    mensaje.setScore1("11");
	    mensaje.setScore2("15");
	    mensaje.setX1(lista.get(lista.size()-1).x);
	    mensaje.setY1(lista.get(lista.size()-1).y);
	    mensaje.setX2(lista.get(lista.size()-2).x);
	    mensaje.setY2(lista.get(lista.size()-2).y);
	    mensaje.setJugador(1);
	    System.out.println("llego2");
	    lectura(mensaje);}
	    	}public void lectura(Molde R) {
		Graphics g = this.getGraphics();
		System.out.println("llego");
		ArrayList<Integer> lineas = new ArrayList<Integer>();
		
		lineas.add(mensaje.getX1());
		lineas.add(mensaje.getY1());
		lineas.add(mensaje.getX2());
		lineas.add(mensaje.getY2());
		
		
		
		if (true) {// validar el jugador
		
			g.setColor( Color.MAGENTA);
			
			g.drawLine((int)lineas.get(0),(int)lineas.get(1),(int)lineas.get(2),(int)lineas.get(3));}
		
		else{
			g.setColor( Color.GREEN);
			g.drawLine((int)lineas.get(0),(int)lineas.get(1),(int)lineas.get(2),(int)lineas.get(3));

		}
    }     */
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables


}
